/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.maximgalushka.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the History service. Represents a row in the &quot;docs_History&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.maximgalushka.service.model.impl.HistoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.maximgalushka.service.model.impl.HistoryImpl}.
 * </p>
 *
 * @author mgalushka
 * @see History
 * @see com.maximgalushka.service.model.impl.HistoryImpl
 * @see com.maximgalushka.service.model.impl.HistoryModelImpl
 * @generated
 */
public interface HistoryModel extends BaseModel<History> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a History model instance should use the {@link History} interface instead.
	 */

	/**
	 * Returns the primary key of this History.
	 *
	 * @return the primary key of this History
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this History.
	 *
	 * @param primaryKey the primary key of this History
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the log ID of this History.
	 *
	 * @return the log ID of this History
	 */
	public long getLogId();

	/**
	 * Sets the log ID of this History.
	 *
	 * @param logId the log ID of this History
	 */
	public void setLogId(long logId);

	/**
	 * Returns the document ID of this History.
	 *
	 * @return the document ID of this History
	 */
	public long getDocumentId();

	/**
	 * Sets the document ID of this History.
	 *
	 * @param documentId the document ID of this History
	 */
	public void setDocumentId(long documentId);

	/**
	 * Returns the user ID of this History.
	 *
	 * @return the user ID of this History
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this History.
	 *
	 * @param userId the user ID of this History
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this History.
	 *
	 * @return the user uuid of this History
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this History.
	 *
	 * @param userUuid the user uuid of this History
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the status of this History.
	 *
	 * @return the status of this History
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this History.
	 *
	 * @param status the status of this History
	 */
	public void setStatus(String status);

	/**
	 * Returns the updated date of this History.
	 *
	 * @return the updated date of this History
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this History.
	 *
	 * @param updatedDate the updated date of this History
	 */
	public void setUpdatedDate(Date updatedDate);

	/**
	 * Returns the comment of this History.
	 *
	 * @return the comment of this History
	 */
	@AutoEscape
	public String getComment();

	/**
	 * Sets the comment of this History.
	 *
	 * @param comment the comment of this History
	 */
	public void setComment(String comment);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(History history);

	public int hashCode();

	public CacheModel<History> toCacheModel();

	public History toEscapedModel();

	public String toString();

	public String toXmlString();
}